# Script for automating the run of the database fixer on merging pull requests

# To install this workflow in your repo:
# 1. Go to Actions > New workflow
# 2. Go to "Set up a workflow yourself"
# 3. Set the name of the new file to "z64_database_update_for_pr.yml"
# 4. Copy and paste the contents of this file to the textbox that says "Enter file contents here"
# 5. Finally, press "Commit changes"

name: Z64 - Update database for PR

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]

    steps:
      - uses: actions/checkout@v3

      - name: Download latest version of database fixer and it's dependencies
        run: |
          curl -o z64_database_fixer.py https://raw.githubusercontent.com/CristobalPenaloza/cristobalpenaloza.github.io/refs/heads/main/z64_repo_kit/z64_database_fixer.py
          curl -o z64_python_requirements.txt https://raw.githubusercontent.com/CristobalPenaloza/cristobalpenaloza.github.io/refs/heads/main/z64_repo_kit/z64_python_requirements.txt
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "z64_python_requirements.txt"
          
      - name: Run checks
        run: python "z64_database_fixer.py" --ci
        
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git add -A
          git commit -m "Database updated for PR #${{ github.event.number }}"
          git pull
          git push